package com.mochurad.coursera.domain.enumeration;

/**
 * The Subject enumeration.
 */
public enum Subject {
    ANALYSIS, ARCHITECTURE, ART, BIOLOGY, BUSINESS, CHEMISTRY, COMMUNICATION, COMPUTER, CULTURE, DATA, DESIGN, EARTH, ECONOMICS, EDUCATION, ELECTRONICS, ENERGY, ENGINEERING, ENVIRONMENTAL, ETHICS, FINANCE, FOOD, HEALTH, HISTORY, HUMANITIES, LANGUAGE, LAW, LIFE, LITERATURE, MANAGEMENT, MATH, MEDICINE, MUSIC, NUTRITION, PHILANTHROPY, PHILOSOPHY, PHYSICS, SAFETY, SCIENCE, SOCIAL, STATISTICS, STUDIES, TEACHER, TRAINING
}
